/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author tavoberry
 */
public class ProgramaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaPrincipal
     */
    public ProgramaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuVehiculo = new javax.swing.JMenu();
        mnuVehiculoRegistrar = new javax.swing.JMenuItem();
        mnuVehiculoSalir = new javax.swing.JMenuItem();
        mnuTaxi = new javax.swing.JMenu();
        mnuTaxiVer = new javax.swing.JMenuItem();
        mnuAutobus = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setLayout(null);

        mnuVehiculo.setMnemonic('v');
        mnuVehiculo.setText("Vehículo");

        mnuVehiculoRegistrar.setMnemonic('r');
        mnuVehiculoRegistrar.setText("Registrar");
        mnuVehiculo.add(mnuVehiculoRegistrar);

        mnuVehiculoSalir.setMnemonic('s');
        mnuVehiculoSalir.setText("Salir");
        mnuVehiculoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculoSalirActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuVehiculoSalir);

        menuBar.add(mnuVehiculo);

        mnuTaxi.setMnemonic('t');
        mnuTaxi.setText("Taxi");

        mnuTaxiVer.setMnemonic('v');
        mnuTaxiVer.setText("Ver");
        mnuTaxi.add(mnuTaxiVer);

        menuBar.add(mnuTaxi);

        mnuAutobus.setMnemonic('a');
        mnuAutobus.setText("Autobús");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        mnuAutobus.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        mnuAutobus.add(aboutMenuItem);

        menuBar.add(mnuAutobus);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVehiculoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculoSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuVehiculoSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAutobus;
    private javax.swing.JMenu mnuTaxi;
    public javax.swing.JMenuItem mnuTaxiVer;
    private javax.swing.JMenu mnuVehiculo;
    public javax.swing.JMenuItem mnuVehiculoRegistrar;
    public javax.swing.JMenuItem mnuVehiculoSalir;
    // End of variables declaration//GEN-END:variables

}
